POST http://127.0.0.1:8000/api/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files"; filename="invoice_sample.jpg"
Content-Type: image/jpeg

< C:\Users\Acer\Downloads\invoices.v8i.yolov8\test\images\39_jpg.rf.c784fb12f26f2adc22bfdfe8be62c70e.jpg
--boundary--

HTTP/1.1 200  - OK
date: Wed, 10 Sep 2025 18:46:29 GMT
server: uvicorn
content-length: 903
content-type: application/json
connection: close
###
POST http://127.0.0.1:8000/api/receipt
Content-Type: application/json

{
  "category": "Healthcare",
  "date": "28 September 2025 at 11:55:22 UTC+5:30",
  "item": "Pharmacy purchase – Vitamins",
  "order_id": "H036",
  "seller_address": "Wellawatte, Colombo",
  "seller_name": "LifeCare Pharmacy",
  "subtotal": 850,
  "tax": 0,
  "total_price": 850,
  "uploaded_date": "28 September 2025 at 12:20:14 UTC+5:30",
  "user_ref": "/Users/WaY6ClkdcLUjWs32fPoaNm4I6v53"
}

HTTP/1.1 200  - OK
date: Sat, 27 Sep 2025 10:21:58 GMT
server: uvicorn
content-length: 48
content-type: application/json
connection: close